# Site settings
title: 农夫的小花园
motto: 好好学习，天天向上
email: 836425475@qq.com
description: nfhy 农夫花园
baseurl: ""
url: "http://nfhy.wang"
twitter_username: 
github_username:  nfhy
disqus: nfhy

# Build settings
markdown: kramdown
highlighter: pygments

